# Generated by Django 2.1.7 on 2020-05-30 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backend', '0010_countwords'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSaveWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cte4_words', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Cte4', verbose_name='保存4级的单词')),
                ('Cte6_words', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Cte6', verbose_name='保存6级的单词')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户保存错词',
            },
        ),
    ]
