# Generated by Django 2.1.7 on 2019-11-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en', models.CharField(max_length=20, unique=True, verbose_name='english')),
                ('ch', models.CharField(max_length=20, unique=True, verbose_name='中文')),
                ('level', models.CharField(max_length=10, verbose_name='等级')),
                ('category', models.CharField(max_length=5, verbose_name='分类')),
            ],
        ),
    ]
