# Generated by Django 3.1.3 on 2020-11-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countcte4', models.IntegerField(default=0, verbose_name='四级单词数')),
                ('countcte6', models.IntegerField(default=0, verbose_name='六级单词数')),
                ('total', models.IntegerField(default=0, verbose_name='总数')),
            ],
        ),
        migrations.CreateModel(
            name='Cte4',
            fields=[
                ('Id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en', models.CharField(max_length=50, verbose_name='english')),
                ('ch', models.CharField(max_length=100, verbose_name='中文')),
                ('category', models.CharField(max_length=10, verbose_name='分类')),
            ],
        ),
        migrations.CreateModel(
            name='Cte6',
            fields=[
                ('Id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en', models.CharField(max_length=50, unique=True, verbose_name='english')),
                ('ch', models.CharField(max_length=100, unique=True, verbose_name='中文')),
                ('category', models.CharField(max_length=10, verbose_name='分类')),
            ],
        ),
    ]
