# Generated by Django 2.1.7 on 2020-04-26 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200426_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cte4',
            name='ch',
            field=models.CharField(max_length=100, verbose_name='中文'),
        ),
        migrations.AlterField(
            model_name='cte4',
            name='en',
            field=models.CharField(max_length=50, verbose_name='english'),
        ),
    ]
