# Generated by Django 2.1.7 on 2020-04-30 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200426_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordAcount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AcountCte4', models.IntegerField(verbose_name='四级单词数量')),
                ('AcountCte6', models.IntegerField(verbose_name='六级单词数量')),
                ('total', models.IntegerField(verbose_name='单词总数量')),
            ],
        ),
        migrations.RenameField(
            model_name='cte4',
            old_name='id',
            new_name='Id',
        ),
        migrations.RenameField(
            model_name='cte6',
            old_name='id',
            new_name='Id',
        ),
    ]
