# Generated by Django 2.1.7 on 2020-04-30 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20200430_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wordacount',
            old_name='AcountCte4',
            new_name='CountCte4',
        ),
        migrations.RenameField(
            model_name='wordacount',
            old_name='AcountCte6',
            new_name='CountCte6',
        ),
    ]
