# Generated by Django 2.1.7 on 2020-04-30 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20200430_1246'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WordAcount',
            new_name='WordCount',
        ),
    ]
