# Generated by Django 2.1.7 on 2020-04-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20200430_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordcount',
            name='CountCte4',
            field=models.IntegerField(default=0, verbose_name='四级单词数量'),
        ),
        migrations.AlterField(
            model_name='wordcount',
            name='CountCte6',
            field=models.IntegerField(default=0, verbose_name='六级单词数量'),
        ),
        migrations.AlterField(
            model_name='wordcount',
            name='total',
            field=models.IntegerField(default=0, verbose_name='单词总数量'),
        ),
    ]
