# Generated by Django 2.1.7 on 2020-04-30 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20200430_1425'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WordCount',
        ),
    ]
