# Generated by Django 2.1.7 on 2020-04-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_delete_wordcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countcte4', models.IntegerField(default=0, verbose_name='四级单词数')),
                ('countcte6', models.IntegerField(default=0, verbose_name='六级单词数')),
                ('total', models.IntegerField(default=0, verbose_name='总数')),
            ],
        ),
    ]
