# Generated by Django 2.1.7 on 2019-11-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('Id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('gender', models.IntegerField(default=1, verbose_name='性别')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='邮箱')),
                ('user_name', models.CharField(max_length=20, unique=True, verbose_name='用户名')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
