# Generated by Django 2.1.7 on 2019-12-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_remove_myuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
