# Generated by Django 2.1.7 on 2020-06-01 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20200601_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='user_name',
            new_name='username',
        ),
    ]
